project:
  type: website
  output-dir: "../public"

website:
  title: "ukbAid"
  navbar:
    right:
      - index.Rmd
      - project-description.qmd
      - text: "Getting started"
        menu:
          - request-access.qmd
          - using-rap.qmd
      - text: "Admin"
        menu:
          - admin.qmd

date: last-modified

format:
  html:
    theme: cosmo
    toc: true



