project:
  type: website
  output-dir: "../public"
  resources:
    - "../public/pkg"

website:
  title: "ukbAid"
  repo-url: https://github.com/steno-aarhus/ukbAid
  repo-actions: [edit, issue]
  navbar:
    pinned: true
    right:
      - index.qmd
      - text: "About"
        menu:
          - project-description.qmd
          - projects.qmd
          - governance.qmd
      - text: "Getting started"
        menu:
          - request-access.qmd
          - initial-setup.qmd
          - using-rap.qmd
          - important-notes.qmd
      - text: "Admin"
        menu:
          - admin.qmd
      - text: "FAQ"
        href: faq.qmd
    tools:
      - icon: box-seam
        href: "/pkg/index.html"
      - icon: github
        href: https://github.com/steno-aarhus/ukbAid
  page-footer:
    center: "Licensed under CC-BY 4.0"

date: last-modified

format:
  html:
    theme:
      - flatly
      - theme.scss
    toc: true
    toc-depth: 2
    mermaid:
      theme: neutral


