project:
  type: website

website:
  title: "ukbAid"
  navbar:
    right:
      - index.Rmd
      - text: "Getting started"
        menu:
          - request-access.qmd
          - using-rap.qmd

date: last-modified

format:
  html:
    theme: cosmo
    toc: true



