project:
  type: website
  output-dir: "../public"
  resources:
    - "../public/pkg"

website:
  title: "ukbAid"
  navbar:
    pinned: true
    right:
      - index.qmd
      - project-description.qmd
      - text: "Getting started"
        menu:
          - request-access.qmd
          - initial-setup.qmd
          - using-rap.qmd
          - important-notes.qmd
      - text: "Admin"
        menu:
          - admin.qmd
          - governance.qmd
      - icon: box-seam
        href: "/pkg/index.html"

date: last-modified

format:
  html:
    theme: flatly
    toc: true
    toc-depth: 2
